server:
  port: 80

eureka:
  client:
    register-with-eureka: false   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群

#设置feign客户端超时时间
ribbon:
  ConnectTimeout: 3000 #建立连接所用时间,用于在网络正常情况下,客户端与服务端连接所用的时间
  ReadTimeout: 5000 #建立连接后,从服务端读取到资源所用的时间

#feign自带了日志监控服务调用情况
logging:
  level:
    com.may.springcloud.service.PaymentFeignService: debug #fegin以什么级别监控什么服务